name: 'Test oasdiff actions'
on:
  pull_request:
  push:
jobs:
 
  oasdiff_breaking:
    runs-on: ubuntu-latest
    name: Test breaking changes
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Running breaking action
        id: test_breaking_changes
        uses: ./breaking
        with:
          base: 'specs/base.yaml'
          revision: 'specs/revision-breaking.yaml'
          fail-on-diff: false
      - name: Test breaking changes action output
        run: |
          delimiter=$(cat /proc/sys/kernel/random/uuid | tr -d '-')
          output=$(cat <<-$delimiter
          ${{ steps.test_breaking_changes.outputs.breaking }}
          $delimiter
          )
          if [ "$output" != "1 breaking changes: 1 error, 0 warning" ]; then
            echo "Expected output '6 breaking changes: 2 error, 4 warning' but got '$output'" >&2
            exit 1
          fi
  
  oasdiff_changelog:
    runs-on: ubuntu-latest
    name: Test generation of changelog
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Running changelog action
        id: spec_diff
        run: |
          delimiter=$(cat /proc/sys/kernel/random/uuid | tr -d '-')
          echo "changelog<<$delimiter" >> $GITHUB_OUTPUT
          output=$(docker run --rm -t tufin/oasdiff changelog \
                   https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test1.yaml \
                   https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test1.yaml)
          echo "$output" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT

      - name: Print changelog
        run: |
          content="<!-- spec_changelog -->\n${{join(steps.spec_diff.outputs.changelog, '\n')}}\n<!-- spec_changelog -->"
          echo "$content"
           
